### ISSUE TITLE
🤔 Deployment guides for beginner

### ISSUE THREAD

**Issue by jd-solanki** [astral-sh/uv-docker-example#21]
Hi 👋🏻 

I used uv docker example and it works fine. However, I would like to understand what is needed to deploy fastapi app from docker using UV?

In example, there's fastapi dev which runs fastapi in dev mode so does just switching to fastapi run will make it for production?

---

I'm asking because when I run fastapi in production it works on https but assets generated using `url_for` still generates http URL 🤷🏻 

I'll be thankful if someone can help me deploy FastAPI app that uses UV & docker. I'm using AWS EC2 instance & nginx for serving FastAPI app.

**Comment by zanieb** [comment]
Yeah now that we did https://github.com/astral-sh/uv-docker-example/pull/17 the only thing you should need to do for production is switch to the `run` command instead of `dev`. You could also consider the [multistage image](https://github.com/astral-sh/uv-docker-example/blob/main/multistage.Dockerfile).

**Comment by zanieb** [comment]
I'm not sure about the `url_for` and HTTP/S behavior. cc @tiangolo

**Comment by jd-solanki** [comment]
Thanks @zanieb for your help in the uv community 🙏🏻 

Also adding this meta tag does the trick along with your inputs & [this](https://fastapi.tiangolo.com/deployment/docker/?h=docker#behind-a-tls-termination-proxy) FastAPI docs.

```html
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
